version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  fastapi:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  pgdata:
